update README
HanniOfHyrule/housemeter pull request #13
Opened 2022-02-15 18:51 UTC by code-knackerin

2022-03-07 13:39 UTC, domnikl requested changes

2022-03-07 13:39 UTC, domnikl commented on src/components/MeasurementsForm.js
> +  console.log(measurementsCssClass);
This console.log can safely be removed.

2022-03-07 13:39 UTC, domnikl commented on src/components/MeasurementsForm.js
> +    console.log(measurementsInput);
Can also be removed.

2022-03-07 13:39 UTC, domnikl commented on src/components/Test.js
> +import React, { useState, useEffect } from "react";
This does not seem to belong here.

2022-03-07 20:45 UTC, domnikl commented on README.md
> +- you can filter the mearurementss
double s 😆

2022-03-08 08:08 UTC, HanniOfHyrule commented on README.md
> +- you can filter the mearurementss
Done!

2022-03-08 08:31 UTC, domnikl approved these changes

2022-03-08 08:31 UTC, merged