Datastore supabase
HanniOfHyrule/housemeter pull request #14
Opened 2022-03-04 10:57 UTC by HanniOfHyrule

2022-03-08 18:21 UTC, domnikl commented on README.md
> +- you can filter the mearurementss
`s` again 😆

2022-03-08 18:21 UTC, domnikl commented on README.md
> +![ScreenShot](/Housemeter.png)
Why is it changed again?

2022-03-08 18:22 UTC, domnikl commented on src/SupabaseClient.js
> +  console.log(error, data);
remove unnecessary `console.log`

2022-03-08 20:54 UTC, HanniOfHyrule commented on README.md
> +- you can filter the mearurementss
✅

2022-03-08 20:55 UTC, HanniOfHyrule commented on README.md
> +![ScreenShot](/Housemeter.png)
i don´t know! kinky!

2022-03-08 20:57 UTC, HanniOfHyrule commented on src/App.js
> +  const [user, setUser] = useState("bla");
🙈

2022-03-08 21:03 UTC, HanniOfHyrule commented on src/components/MeasurementsTable.js
> +                key={Number.toString()}
right, it doesn´t need a key.

2022-03-09 09:05 UTC, HanniOfHyrule commented on src/App.js
> +  const [user, setUser] = useState("null");
only `null`

2022-03-09 12:18 UTC, domnikl requested changes

2022-03-09 12:18 UTC, domnikl commented on src/SupabaseClient.js
> +// export async function deleteData() {
shouldn't be here

2022-03-09 12:18 UTC, domnikl commented on src/components/MeasurementsTable.js
> +              key={v4}
The key should be set to `reading.id`

2022-03-16 12:48 UTC, domnikl approved these changes

2022-03-16 12:48 UTC, merged