Validity
HanniOfHyrule/housemeter pull request #22
Opened 2022-06-01 07:48 UTC by HanniOfHyrule

2022-06-10 13:32 UTC, domnikl requested changes

2022-06-10 13:32 UTC, domnikl commented on src/interfaceMeasurement.ts
> +  date: string | number;
Why is it either a string or number? Should bei string or maybe use a `Date` object here?

2022-06-10 13:32 UTC, domnikl commented on src/SupabaseClient.tsx
> +    throw new Error("Error, data cant be null");
After much thought i don't think that's a good approach as it is an async function, I don't know how that behaves with `throw` as it might swallow the exception and the user might not see anything from it. Would rather just to return the Promise to the caller of `addMeasurements` and handle excecptions there with something alone these lines:

```js
addMeasurement(measurement)
  .then(() => reloadOrWhatever())
  .catch((error) => setError(error)); // setError would be a function returned from a useState call and display the error for some seconds to the user.
```

2022-06-10 13:32 UTC, domnikl commented on src/components/Form/MeasurementsForm.tsx
> +    //TODO: interface
please use the interface here

2022-06-10 13:32 UTC, domnikl commented on src/interfaceMeasurement.ts
> +export interface Measurement {
Why did you add the `interface...` prefix for the file name?

2022-06-10 13:32 UTC, domnikl commented on src/components/MeasurementsTable.tsx
> +    deleteMeasurements(reading);
Please be careful: naming the function in plural gives me as an outsider the impression that multiple measurements could be deleted. Also please rename `reading` to `measurement`

2022-06-10 13:32 UTC, domnikl commented on src/components/Form/MeasurementsForm.module.css
> +.submitButton:disabled,
Maybe it makes sense to generalize that and not tie it to a submitButton class but to style all elements with `::disabled` state like that.

2022-06-11 06:42 UTC, HanniOfHyrule commented on src/interfaceMeasurement.ts
> +  date: string | number;
a string comes out of the date object. That was my problem and after the getTime methode it is a number.

2022-06-14 08:10 UTC, HanniOfHyrule commented on src/interfaceMeasurement.ts
> +  date: string | number;
Done

2022-06-14 08:10 UTC, HanniOfHyrule commented on src/components/Form/MeasurementsForm.tsx
> +    //TODO: interface
Done

2022-07-04 11:30 UTC, HanniOfHyrule commented on src/components/Form/MeasurementsForm.module.css
> +.submitButton:disabled,
Why? It is a pseudoclass selector ant not a pseudoelement. And we have only one button.

2022-07-07 13:59 UTC, merged